//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHackMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class citation
    {
        public short id { get; set; }
        [Display(Name = "Ticket Number")]
        public int citation_number { get; set; }
        public Nullable<System.DateTime> citation_date { get; set; }
        [Display(Name = "First Name")]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
        public string last_name { get; set; }
        [Display(Name = "DOB")]
        public Nullable<System.DateTime> date_of_birth { get; set; }
        [Display(Name = "Address")]
        public string defendant_address { get; set; }
        [Display(Name = "City")]
        public string defendant_city { get; set; }
        [Display(Name = "State")]
        public string defendant_state { get; set; }
        [Display(Name = "Driver's License Number")]
        public string drivers_license_number { get; set; }
        [Display(Name = "Court Date")]
        public Nullable<System.DateTime> court_date { get; set; }
        [Display(Name = "Court Location")]
        public string court_location { get; set; }
        [Display(Name = "Court Address")]
        public string court_address { get; set; }
        public virtual ICollection<violation> Violations { get; set; }
    }
}
